[package]
name = "tachyon"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"

[features]
time_travel = []
default = ["time_travel"]
